AWSTemplateFormatVersion: '2010-09-09'
Description: Security group allowing SSH from the whole internet

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  AdminGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub 'admin-${AWS::StackName}'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
